# Automatically generated file. DO NOT MODIFY
#
# This file is generated by device/xiaomi/pipa/setup-makefiles.sh

AB_OTA_PARTITIONS += \
    abl \
    aop \
    bluetooth \
    cmnlib \
    cmnlib64 \
    devcfg \
    dsp \
    featenabler \
    hyp \
    imagefv \
    keymaster \
    modem \
    qupfw \
    tz \
    uefisecapp \
    xbl \
    xbl_config
